/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PartnerApplyRouteImport } from './routes/partner-apply'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as AgreementRouteImport } from './routes/agreement'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as ApiVerifyPaymentRouteImport } from './routes/api.verify-payment'
import { Route as ApiVerifyBankRouteImport } from './routes/api.verify-bank'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api.telegram-webhook'
import { Route as ApiSquadWebhookRouteImport } from './routes/api.squad-webhook'
import { Route as ApiSendEmailRouteImport } from './routes/api.send-email'
import { Route as ApiProvisionAccountRouteImport } from './routes/api.provision-account'
import { Route as ApiPartnerApplicationRouteImport } from './routes/api.partner-application'
import { Route as ApiNotifyNewPurchaseRouteImport } from './routes/api.notify-new-purchase'
import { Route as ApiInitializePaymentRouteImport } from './routes/api.initialize-payment'
import { Route as ApiExchangeRateRouteImport } from './routes/api.exchange-rate'
import { Route as ApiDeliverAccountRouteImport } from './routes/api.deliver-account'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedAffiliateRouteImport } from './routes/_authenticated/affiliate'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AuthenticatedCommunityIndexRouteImport } from './routes/_authenticated/community.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as ApiPublicPushEventRouteImport } from './routes/api.public.push-event'
import { Route as ApiAdminSetExchangeRateRouteImport } from './routes/api.admin.set-exchange-rate'
import { Route as ApiAdminPoolRouteImport } from './routes/api.admin.pool'
import { Route as ApiAdminDeleteRequestRouteImport } from './routes/api.admin.delete-request'
import { Route as AuthenticatedCommunitySlugRouteImport } from './routes/_authenticated/community.$slug'
import { Route as AdminAdminTicketsRouteImport } from './routes/_admin/admin.tickets'
import { Route as AdminAdminSocialRouteImport } from './routes/_admin/admin.social'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminPoolRouteImport } from './routes/_admin/admin.pool'
import { Route as AdminAdminPendingRouteImport } from './routes/_admin/admin.pending'
import { Route as AdminAdminPayoutsRouteImport } from './routes/_admin/admin.payouts'
import { Route as AdminAdminPartnersRouteImport } from './routes/_admin/admin.partners'
import { Route as AdminAdminDiscountsRouteImport } from './routes/_admin/admin.discounts'
import { Route as AdminAdminChallengesRouteImport } from './routes/_admin/admin.challenges'
import { Route as AdminAdminAiContentRouteImport } from './routes/_admin/admin.ai-content'
import { Route as AdminAdminAffiliateRouteImport } from './routes/_admin/admin.affiliate'
import { Route as AdminAdminAccountsRouteImport } from './routes/_admin/admin.accounts'
import { Route as ApiPublicCronSyncEquityV2RouteImport } from './routes/api.public.cron.sync-equity-v2'
import { Route as ApiPublicCronSyncEquityRouteImport } from './routes/api.public.cron.sync-equity'
import { Route as ApiPublicCronRefreshLeaderboardRouteImport } from './routes/api.public.cron.refresh-leaderboard'
import { Route as ApiPublicCronReconcilePaymentsRouteImport } from './routes/api.public.cron.reconcile-payments'
import { Route as ApiPublicCronHandleWeekendViolationRouteImport } from './routes/api.public.cron.handle-weekend-violation'
import { Route as ApiPublicCronHandleScalpingRouteImport } from './routes/api.public.cron.handle-scalping'
import { Route as ApiPublicCronHandlePositionsViolationRouteImport } from './routes/api.public.cron.handle-positions-violation'
import { Route as ApiPublicCronHandleNewsViolationRouteImport } from './routes/api.public.cron.handle-news-violation'
import { Route as ApiPublicCronDailyContentRouteImport } from './routes/api.public.cron.daily-content'
import { Route as ApiPublicCronAutoProgressPhaseRouteImport } from './routes/api.public.cron.auto-progress-phase'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerApplyRoute = PartnerApplyRouteImport.update({
  id: '/partner-apply',
  path: '/partner-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementRoute = AgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPaymentRoute = ApiVerifyPaymentRouteImport.update({
  id: '/api/verify-payment',
  path: '/api/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyBankRoute = ApiVerifyBankRouteImport.update({
  id: '/api/verify-bank',
  path: '/api/verify-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram-webhook',
  path: '/api/telegram-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSquadWebhookRoute = ApiSquadWebhookRouteImport.update({
  id: '/api/squad-webhook',
  path: '/api/squad-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/send-email',
  path: '/api/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvisionAccountRoute = ApiProvisionAccountRouteImport.update({
  id: '/api/provision-account',
  path: '/api/provision-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPartnerApplicationRoute = ApiPartnerApplicationRouteImport.update({
  id: '/api/partner-application',
  path: '/api/partner-application',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyNewPurchaseRoute = ApiNotifyNewPurchaseRouteImport.update({
  id: '/api/notify-new-purchase',
  path: '/api/notify-new-purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInitializePaymentRoute = ApiInitializePaymentRouteImport.update({
  id: '/api/initialize-payment',
  path: '/api/initialize-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeRateRoute = ApiExchangeRateRouteImport.update({
  id: '/api/exchange-rate',
  path: '/api/exchange-rate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliverAccountRoute = ApiDeliverAccountRouteImport.update({
  id: '/api/deliver-account',
  path: '/api/deliver-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAffiliateRoute = AuthenticatedAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedCommunityIndexRoute =
  AuthenticatedCommunityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const ApiPublicPushEventRoute = ApiPublicPushEventRouteImport.update({
  id: '/api/public/push-event',
  path: '/api/public/push-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSetExchangeRateRoute = ApiAdminSetExchangeRateRouteImport.update({
  id: '/api/admin/set-exchange-rate',
  path: '/api/admin/set-exchange-rate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPoolRoute = ApiAdminPoolRouteImport.update({
  id: '/api/admin/pool',
  path: '/api/admin/pool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeleteRequestRoute = ApiAdminDeleteRequestRouteImport.update({
  id: '/api/admin/delete-request',
  path: '/api/admin/delete-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommunitySlugRoute =
  AuthenticatedCommunitySlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AdminAdminTicketsRoute = AdminAdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSocialRoute = AdminAdminSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPoolRoute = AdminAdminPoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPendingRoute = AdminAdminPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPayoutsRoute = AdminAdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPartnersRoute = AdminAdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminDiscountsRoute = AdminAdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminChallengesRoute = AdminAdminChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAiContentRoute = AdminAdminAiContentRouteImport.update({
  id: '/ai-content',
  path: '/ai-content',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAffiliateRoute = AdminAdminAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAccountsRoute = AdminAdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminAdminRoute,
} as any)
const ApiPublicCronSyncEquityV2Route =
  ApiPublicCronSyncEquityV2RouteImport.update({
    id: '/api/public/cron/sync-equity-v2',
    path: '/api/public/cron/sync-equity-v2',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSyncEquityRoute = ApiPublicCronSyncEquityRouteImport.update({
  id: '/api/public/cron/sync-equity',
  path: '/api/public/cron/sync-equity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRefreshLeaderboardRoute =
  ApiPublicCronRefreshLeaderboardRouteImport.update({
    id: '/api/public/cron/refresh-leaderboard',
    path: '/api/public/cron/refresh-leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronReconcilePaymentsRoute =
  ApiPublicCronReconcilePaymentsRouteImport.update({
    id: '/api/public/cron/reconcile-payments',
    path: '/api/public/cron/reconcile-payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronHandleWeekendViolationRoute =
  ApiPublicCronHandleWeekendViolationRouteImport.update({
    id: '/api/public/cron/handle-weekend-violation',
    path: '/api/public/cron/handle-weekend-violation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronHandleScalpingRoute =
  ApiPublicCronHandleScalpingRouteImport.update({
    id: '/api/public/cron/handle-scalping',
    path: '/api/public/cron/handle-scalping',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronHandlePositionsViolationRoute =
  ApiPublicCronHandlePositionsViolationRouteImport.update({
    id: '/api/public/cron/handle-positions-violation',
    path: '/api/public/cron/handle-positions-violation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronHandleNewsViolationRoute =
  ApiPublicCronHandleNewsViolationRouteImport.update({
    id: '/api/public/cron/handle-news-violation',
    path: '/api/public/cron/handle-news-violation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDailyContentRoute =
  ApiPublicCronDailyContentRouteImport.update({
    id: '/api/public/cron/daily-content',
    path: '/api/public/cron/daily-content',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronAutoProgressPhaseRoute =
  ApiPublicCronAutoProgressPhaseRouteImport.update({
    id: '/api/public/cron/auto-progress-phase',
    path: '/api/public/cron/auto-progress-phase',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agreement': typeof AgreementRoute
  '/buy': typeof BuyRoute
  '/discord': typeof DiscordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/partner-apply': typeof PartnerApplyRoute
  '/partners': typeof PartnersRoute
  '/rules': typeof RulesRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/community': typeof AuthenticatedCommunityRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/api/deliver-account': typeof ApiDeliverAccountRoute
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/initialize-payment': typeof ApiInitializePaymentRoute
  '/api/notify-new-purchase': typeof ApiNotifyNewPurchaseRoute
  '/api/partner-application': typeof ApiPartnerApplicationRoute
  '/api/provision-account': typeof ApiProvisionAccountRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/squad-webhook': typeof ApiSquadWebhookRoute
  '/api/telegram-webhook': typeof ApiTelegramWebhookRoute
  '/api/verify-bank': typeof ApiVerifyBankRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/admin/accounts': typeof AdminAdminAccountsRoute
  '/admin/affiliate': typeof AdminAdminAffiliateRoute
  '/admin/ai-content': typeof AdminAdminAiContentRoute
  '/admin/challenges': typeof AdminAdminChallengesRoute
  '/admin/discounts': typeof AdminAdminDiscountsRoute
  '/admin/partners': typeof AdminAdminPartnersRoute
  '/admin/payouts': typeof AdminAdminPayoutsRoute
  '/admin/pending': typeof AdminAdminPendingRoute
  '/admin/pool': typeof AdminAdminPoolRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/social': typeof AdminAdminSocialRoute
  '/admin/tickets': typeof AdminAdminTicketsRoute
  '/community/$slug': typeof AuthenticatedCommunitySlugRoute
  '/api/admin/delete-request': typeof ApiAdminDeleteRequestRoute
  '/api/admin/pool': typeof ApiAdminPoolRoute
  '/api/admin/set-exchange-rate': typeof ApiAdminSetExchangeRateRoute
  '/api/public/push-event': typeof ApiPublicPushEventRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/community/': typeof AuthenticatedCommunityIndexRoute
  '/api/public/cron/auto-progress-phase': typeof ApiPublicCronAutoProgressPhaseRoute
  '/api/public/cron/daily-content': typeof ApiPublicCronDailyContentRoute
  '/api/public/cron/handle-news-violation': typeof ApiPublicCronHandleNewsViolationRoute
  '/api/public/cron/handle-positions-violation': typeof ApiPublicCronHandlePositionsViolationRoute
  '/api/public/cron/handle-scalping': typeof ApiPublicCronHandleScalpingRoute
  '/api/public/cron/handle-weekend-violation': typeof ApiPublicCronHandleWeekendViolationRoute
  '/api/public/cron/reconcile-payments': typeof ApiPublicCronReconcilePaymentsRoute
  '/api/public/cron/refresh-leaderboard': typeof ApiPublicCronRefreshLeaderboardRoute
  '/api/public/cron/sync-equity': typeof ApiPublicCronSyncEquityRoute
  '/api/public/cron/sync-equity-v2': typeof ApiPublicCronSyncEquityV2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agreement': typeof AgreementRoute
  '/buy': typeof BuyRoute
  '/discord': typeof DiscordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/partner-apply': typeof PartnerApplyRoute
  '/partners': typeof PartnersRoute
  '/rules': typeof RulesRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/api/deliver-account': typeof ApiDeliverAccountRoute
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/initialize-payment': typeof ApiInitializePaymentRoute
  '/api/notify-new-purchase': typeof ApiNotifyNewPurchaseRoute
  '/api/partner-application': typeof ApiPartnerApplicationRoute
  '/api/provision-account': typeof ApiProvisionAccountRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/squad-webhook': typeof ApiSquadWebhookRoute
  '/api/telegram-webhook': typeof ApiTelegramWebhookRoute
  '/api/verify-bank': typeof ApiVerifyBankRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/admin/accounts': typeof AdminAdminAccountsRoute
  '/admin/affiliate': typeof AdminAdminAffiliateRoute
  '/admin/ai-content': typeof AdminAdminAiContentRoute
  '/admin/challenges': typeof AdminAdminChallengesRoute
  '/admin/discounts': typeof AdminAdminDiscountsRoute
  '/admin/partners': typeof AdminAdminPartnersRoute
  '/admin/payouts': typeof AdminAdminPayoutsRoute
  '/admin/pending': typeof AdminAdminPendingRoute
  '/admin/pool': typeof AdminAdminPoolRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/social': typeof AdminAdminSocialRoute
  '/admin/tickets': typeof AdminAdminTicketsRoute
  '/community/$slug': typeof AuthenticatedCommunitySlugRoute
  '/api/admin/delete-request': typeof ApiAdminDeleteRequestRoute
  '/api/admin/pool': typeof ApiAdminPoolRoute
  '/api/admin/set-exchange-rate': typeof ApiAdminSetExchangeRateRoute
  '/api/public/push-event': typeof ApiPublicPushEventRoute
  '/admin': typeof AdminAdminIndexRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
  '/api/public/cron/auto-progress-phase': typeof ApiPublicCronAutoProgressPhaseRoute
  '/api/public/cron/daily-content': typeof ApiPublicCronDailyContentRoute
  '/api/public/cron/handle-news-violation': typeof ApiPublicCronHandleNewsViolationRoute
  '/api/public/cron/handle-positions-violation': typeof ApiPublicCronHandlePositionsViolationRoute
  '/api/public/cron/handle-scalping': typeof ApiPublicCronHandleScalpingRoute
  '/api/public/cron/handle-weekend-violation': typeof ApiPublicCronHandleWeekendViolationRoute
  '/api/public/cron/reconcile-payments': typeof ApiPublicCronReconcilePaymentsRoute
  '/api/public/cron/refresh-leaderboard': typeof ApiPublicCronRefreshLeaderboardRoute
  '/api/public/cron/sync-equity': typeof ApiPublicCronSyncEquityRoute
  '/api/public/cron/sync-equity-v2': typeof ApiPublicCronSyncEquityV2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/agreement': typeof AgreementRoute
  '/buy': typeof BuyRoute
  '/discord': typeof DiscordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/partner-apply': typeof PartnerApplyRoute
  '/partners': typeof PartnersRoute
  '/rules': typeof RulesRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/affiliate': typeof AuthenticatedAffiliateRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/partner': typeof AuthenticatedPartnerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/api/deliver-account': typeof ApiDeliverAccountRoute
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/initialize-payment': typeof ApiInitializePaymentRoute
  '/api/notify-new-purchase': typeof ApiNotifyNewPurchaseRoute
  '/api/partner-application': typeof ApiPartnerApplicationRoute
  '/api/provision-account': typeof ApiProvisionAccountRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/squad-webhook': typeof ApiSquadWebhookRoute
  '/api/telegram-webhook': typeof ApiTelegramWebhookRoute
  '/api/verify-bank': typeof ApiVerifyBankRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/_admin/admin/accounts': typeof AdminAdminAccountsRoute
  '/_admin/admin/affiliate': typeof AdminAdminAffiliateRoute
  '/_admin/admin/ai-content': typeof AdminAdminAiContentRoute
  '/_admin/admin/challenges': typeof AdminAdminChallengesRoute
  '/_admin/admin/discounts': typeof AdminAdminDiscountsRoute
  '/_admin/admin/partners': typeof AdminAdminPartnersRoute
  '/_admin/admin/payouts': typeof AdminAdminPayoutsRoute
  '/_admin/admin/pending': typeof AdminAdminPendingRoute
  '/_admin/admin/pool': typeof AdminAdminPoolRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/social': typeof AdminAdminSocialRoute
  '/_admin/admin/tickets': typeof AdminAdminTicketsRoute
  '/_authenticated/community/$slug': typeof AuthenticatedCommunitySlugRoute
  '/api/admin/delete-request': typeof ApiAdminDeleteRequestRoute
  '/api/admin/pool': typeof ApiAdminPoolRoute
  '/api/admin/set-exchange-rate': typeof ApiAdminSetExchangeRateRoute
  '/api/public/push-event': typeof ApiPublicPushEventRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRoute
  '/api/public/cron/auto-progress-phase': typeof ApiPublicCronAutoProgressPhaseRoute
  '/api/public/cron/daily-content': typeof ApiPublicCronDailyContentRoute
  '/api/public/cron/handle-news-violation': typeof ApiPublicCronHandleNewsViolationRoute
  '/api/public/cron/handle-positions-violation': typeof ApiPublicCronHandlePositionsViolationRoute
  '/api/public/cron/handle-scalping': typeof ApiPublicCronHandleScalpingRoute
  '/api/public/cron/handle-weekend-violation': typeof ApiPublicCronHandleWeekendViolationRoute
  '/api/public/cron/reconcile-payments': typeof ApiPublicCronReconcilePaymentsRoute
  '/api/public/cron/refresh-leaderboard': typeof ApiPublicCronRefreshLeaderboardRoute
  '/api/public/cron/sync-equity': typeof ApiPublicCronSyncEquityRoute
  '/api/public/cron/sync-equity-v2': typeof ApiPublicCronSyncEquityV2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agreement'
    | '/buy'
    | '/discord'
    | '/leaderboard'
    | '/partner-apply'
    | '/partners'
    | '/rules'
    | '/admin'
    | '/affiliate'
    | '/community'
    | '/dashboard'
    | '/partner'
    | '/profile'
    | '/stats'
    | '/support'
    | '/api/deliver-account'
    | '/api/exchange-rate'
    | '/api/initialize-payment'
    | '/api/notify-new-purchase'
    | '/api/partner-application'
    | '/api/provision-account'
    | '/api/send-email'
    | '/api/squad-webhook'
    | '/api/telegram-webhook'
    | '/api/verify-bank'
    | '/api/verify-payment'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/payment/callback'
    | '/admin/accounts'
    | '/admin/affiliate'
    | '/admin/ai-content'
    | '/admin/challenges'
    | '/admin/discounts'
    | '/admin/partners'
    | '/admin/payouts'
    | '/admin/pending'
    | '/admin/pool'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/tickets'
    | '/community/$slug'
    | '/api/admin/delete-request'
    | '/api/admin/pool'
    | '/api/admin/set-exchange-rate'
    | '/api/public/push-event'
    | '/admin/'
    | '/community/'
    | '/api/public/cron/auto-progress-phase'
    | '/api/public/cron/daily-content'
    | '/api/public/cron/handle-news-violation'
    | '/api/public/cron/handle-positions-violation'
    | '/api/public/cron/handle-scalping'
    | '/api/public/cron/handle-weekend-violation'
    | '/api/public/cron/reconcile-payments'
    | '/api/public/cron/refresh-leaderboard'
    | '/api/public/cron/sync-equity'
    | '/api/public/cron/sync-equity-v2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agreement'
    | '/buy'
    | '/discord'
    | '/leaderboard'
    | '/partner-apply'
    | '/partners'
    | '/rules'
    | '/affiliate'
    | '/dashboard'
    | '/partner'
    | '/profile'
    | '/stats'
    | '/support'
    | '/api/deliver-account'
    | '/api/exchange-rate'
    | '/api/initialize-payment'
    | '/api/notify-new-purchase'
    | '/api/partner-application'
    | '/api/provision-account'
    | '/api/send-email'
    | '/api/squad-webhook'
    | '/api/telegram-webhook'
    | '/api/verify-bank'
    | '/api/verify-payment'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/payment/callback'
    | '/admin/accounts'
    | '/admin/affiliate'
    | '/admin/ai-content'
    | '/admin/challenges'
    | '/admin/discounts'
    | '/admin/partners'
    | '/admin/payouts'
    | '/admin/pending'
    | '/admin/pool'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/tickets'
    | '/community/$slug'
    | '/api/admin/delete-request'
    | '/api/admin/pool'
    | '/api/admin/set-exchange-rate'
    | '/api/public/push-event'
    | '/admin'
    | '/community'
    | '/api/public/cron/auto-progress-phase'
    | '/api/public/cron/daily-content'
    | '/api/public/cron/handle-news-violation'
    | '/api/public/cron/handle-positions-violation'
    | '/api/public/cron/handle-scalping'
    | '/api/public/cron/handle-weekend-violation'
    | '/api/public/cron/reconcile-payments'
    | '/api/public/cron/refresh-leaderboard'
    | '/api/public/cron/sync-equity'
    | '/api/public/cron/sync-equity-v2'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/agreement'
    | '/buy'
    | '/discord'
    | '/leaderboard'
    | '/partner-apply'
    | '/partners'
    | '/rules'
    | '/_admin/admin'
    | '/_authenticated/affiliate'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/partner'
    | '/_authenticated/profile'
    | '/_authenticated/stats'
    | '/_authenticated/support'
    | '/api/deliver-account'
    | '/api/exchange-rate'
    | '/api/initialize-payment'
    | '/api/notify-new-purchase'
    | '/api/partner-application'
    | '/api/provision-account'
    | '/api/send-email'
    | '/api/squad-webhook'
    | '/api/telegram-webhook'
    | '/api/verify-bank'
    | '/api/verify-payment'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/payment/callback'
    | '/_admin/admin/accounts'
    | '/_admin/admin/affiliate'
    | '/_admin/admin/ai-content'
    | '/_admin/admin/challenges'
    | '/_admin/admin/discounts'
    | '/_admin/admin/partners'
    | '/_admin/admin/payouts'
    | '/_admin/admin/pending'
    | '/_admin/admin/pool'
    | '/_admin/admin/settings'
    | '/_admin/admin/social'
    | '/_admin/admin/tickets'
    | '/_authenticated/community/$slug'
    | '/api/admin/delete-request'
    | '/api/admin/pool'
    | '/api/admin/set-exchange-rate'
    | '/api/public/push-event'
    | '/_admin/admin/'
    | '/_authenticated/community/'
    | '/api/public/cron/auto-progress-phase'
    | '/api/public/cron/daily-content'
    | '/api/public/cron/handle-news-violation'
    | '/api/public/cron/handle-positions-violation'
    | '/api/public/cron/handle-scalping'
    | '/api/public/cron/handle-weekend-violation'
    | '/api/public/cron/reconcile-payments'
    | '/api/public/cron/refresh-leaderboard'
    | '/api/public/cron/sync-equity'
    | '/api/public/cron/sync-equity-v2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AgreementRoute: typeof AgreementRoute
  BuyRoute: typeof BuyRoute
  DiscordRoute: typeof DiscordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PartnerApplyRoute: typeof PartnerApplyRoute
  PartnersRoute: typeof PartnersRoute
  RulesRoute: typeof RulesRoute
  ApiDeliverAccountRoute: typeof ApiDeliverAccountRoute
  ApiExchangeRateRoute: typeof ApiExchangeRateRoute
  ApiInitializePaymentRoute: typeof ApiInitializePaymentRoute
  ApiNotifyNewPurchaseRoute: typeof ApiNotifyNewPurchaseRoute
  ApiPartnerApplicationRoute: typeof ApiPartnerApplicationRoute
  ApiProvisionAccountRoute: typeof ApiProvisionAccountRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  ApiSquadWebhookRoute: typeof ApiSquadWebhookRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiVerifyBankRoute: typeof ApiVerifyBankRoute
  ApiVerifyPaymentRoute: typeof ApiVerifyPaymentRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  ApiAdminDeleteRequestRoute: typeof ApiAdminDeleteRequestRoute
  ApiAdminPoolRoute: typeof ApiAdminPoolRoute
  ApiAdminSetExchangeRateRoute: typeof ApiAdminSetExchangeRateRoute
  ApiPublicPushEventRoute: typeof ApiPublicPushEventRoute
  ApiPublicCronAutoProgressPhaseRoute: typeof ApiPublicCronAutoProgressPhaseRoute
  ApiPublicCronDailyContentRoute: typeof ApiPublicCronDailyContentRoute
  ApiPublicCronHandleNewsViolationRoute: typeof ApiPublicCronHandleNewsViolationRoute
  ApiPublicCronHandlePositionsViolationRoute: typeof ApiPublicCronHandlePositionsViolationRoute
  ApiPublicCronHandleScalpingRoute: typeof ApiPublicCronHandleScalpingRoute
  ApiPublicCronHandleWeekendViolationRoute: typeof ApiPublicCronHandleWeekendViolationRoute
  ApiPublicCronReconcilePaymentsRoute: typeof ApiPublicCronReconcilePaymentsRoute
  ApiPublicCronRefreshLeaderboardRoute: typeof ApiPublicCronRefreshLeaderboardRoute
  ApiPublicCronSyncEquityRoute: typeof ApiPublicCronSyncEquityRoute
  ApiPublicCronSyncEquityV2Route: typeof ApiPublicCronSyncEquityV2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-apply': {
      id: '/partner-apply'
      path: '/partner-apply'
      fullPath: '/partner-apply'
      preLoaderRoute: typeof PartnerApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement': {
      id: '/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof AgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-payment': {
      id: '/api/verify-payment'
      path: '/api/verify-payment'
      fullPath: '/api/verify-payment'
      preLoaderRoute: typeof ApiVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-bank': {
      id: '/api/verify-bank'
      path: '/api/verify-bank'
      fullPath: '/api/verify-bank'
      preLoaderRoute: typeof ApiVerifyBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram-webhook': {
      id: '/api/telegram-webhook'
      path: '/api/telegram-webhook'
      fullPath: '/api/telegram-webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/squad-webhook': {
      id: '/api/squad-webhook'
      path: '/api/squad-webhook'
      fullPath: '/api/squad-webhook'
      preLoaderRoute: typeof ApiSquadWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-email': {
      id: '/api/send-email'
      path: '/api/send-email'
      fullPath: '/api/send-email'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provision-account': {
      id: '/api/provision-account'
      path: '/api/provision-account'
      fullPath: '/api/provision-account'
      preLoaderRoute: typeof ApiProvisionAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/partner-application': {
      id: '/api/partner-application'
      path: '/api/partner-application'
      fullPath: '/api/partner-application'
      preLoaderRoute: typeof ApiPartnerApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-new-purchase': {
      id: '/api/notify-new-purchase'
      path: '/api/notify-new-purchase'
      fullPath: '/api/notify-new-purchase'
      preLoaderRoute: typeof ApiNotifyNewPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/initialize-payment': {
      id: '/api/initialize-payment'
      path: '/api/initialize-payment'
      fullPath: '/api/initialize-payment'
      preLoaderRoute: typeof ApiInitializePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exchange-rate': {
      id: '/api/exchange-rate'
      path: '/api/exchange-rate'
      fullPath: '/api/exchange-rate'
      preLoaderRoute: typeof ApiExchangeRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deliver-account': {
      id: '/api/deliver-account'
      path: '/api/deliver-account'
      fullPath: '/api/deliver-account'
      preLoaderRoute: typeof ApiDeliverAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliate': {
      id: '/_authenticated/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AuthenticatedAffiliateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/api/public/push-event': {
      id: '/api/public/push-event'
      path: '/api/public/push-event'
      fullPath: '/api/public/push-event'
      preLoaderRoute: typeof ApiPublicPushEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/set-exchange-rate': {
      id: '/api/admin/set-exchange-rate'
      path: '/api/admin/set-exchange-rate'
      fullPath: '/api/admin/set-exchange-rate'
      preLoaderRoute: typeof ApiAdminSetExchangeRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pool': {
      id: '/api/admin/pool'
      path: '/api/admin/pool'
      fullPath: '/api/admin/pool'
      preLoaderRoute: typeof ApiAdminPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-request': {
      id: '/api/admin/delete-request'
      path: '/api/admin/delete-request'
      fullPath: '/api/admin/delete-request'
      preLoaderRoute: typeof ApiAdminDeleteRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/community/$slug': {
      id: '/_authenticated/community/$slug'
      path: '/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof AuthenticatedCommunitySlugRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_admin/admin/tickets': {
      id: '/_admin/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminAdminTicketsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/social': {
      id: '/_admin/admin/social'
      path: '/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AdminAdminSocialRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/pool': {
      id: '/_admin/admin/pool'
      path: '/pool'
      fullPath: '/admin/pool'
      preLoaderRoute: typeof AdminAdminPoolRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/pending': {
      id: '/_admin/admin/pending'
      path: '/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AdminAdminPendingRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/payouts': {
      id: '/_admin/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminAdminPayoutsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/partners': {
      id: '/_admin/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminAdminPartnersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/discounts': {
      id: '/_admin/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminAdminDiscountsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/challenges': {
      id: '/_admin/admin/challenges'
      path: '/challenges'
      fullPath: '/admin/challenges'
      preLoaderRoute: typeof AdminAdminChallengesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/ai-content': {
      id: '/_admin/admin/ai-content'
      path: '/ai-content'
      fullPath: '/admin/ai-content'
      preLoaderRoute: typeof AdminAdminAiContentRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/affiliate': {
      id: '/_admin/admin/affiliate'
      path: '/affiliate'
      fullPath: '/admin/affiliate'
      preLoaderRoute: typeof AdminAdminAffiliateRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/accounts': {
      id: '/_admin/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAdminAccountsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/api/public/cron/sync-equity-v2': {
      id: '/api/public/cron/sync-equity-v2'
      path: '/api/public/cron/sync-equity-v2'
      fullPath: '/api/public/cron/sync-equity-v2'
      preLoaderRoute: typeof ApiPublicCronSyncEquityV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-equity': {
      id: '/api/public/cron/sync-equity'
      path: '/api/public/cron/sync-equity'
      fullPath: '/api/public/cron/sync-equity'
      preLoaderRoute: typeof ApiPublicCronSyncEquityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-leaderboard': {
      id: '/api/public/cron/refresh-leaderboard'
      path: '/api/public/cron/refresh-leaderboard'
      fullPath: '/api/public/cron/refresh-leaderboard'
      preLoaderRoute: typeof ApiPublicCronRefreshLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/reconcile-payments': {
      id: '/api/public/cron/reconcile-payments'
      path: '/api/public/cron/reconcile-payments'
      fullPath: '/api/public/cron/reconcile-payments'
      preLoaderRoute: typeof ApiPublicCronReconcilePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/handle-weekend-violation': {
      id: '/api/public/cron/handle-weekend-violation'
      path: '/api/public/cron/handle-weekend-violation'
      fullPath: '/api/public/cron/handle-weekend-violation'
      preLoaderRoute: typeof ApiPublicCronHandleWeekendViolationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/handle-scalping': {
      id: '/api/public/cron/handle-scalping'
      path: '/api/public/cron/handle-scalping'
      fullPath: '/api/public/cron/handle-scalping'
      preLoaderRoute: typeof ApiPublicCronHandleScalpingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/handle-positions-violation': {
      id: '/api/public/cron/handle-positions-violation'
      path: '/api/public/cron/handle-positions-violation'
      fullPath: '/api/public/cron/handle-positions-violation'
      preLoaderRoute: typeof ApiPublicCronHandlePositionsViolationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/handle-news-violation': {
      id: '/api/public/cron/handle-news-violation'
      path: '/api/public/cron/handle-news-violation'
      fullPath: '/api/public/cron/handle-news-violation'
      preLoaderRoute: typeof ApiPublicCronHandleNewsViolationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-content': {
      id: '/api/public/cron/daily-content'
      path: '/api/public/cron/daily-content'
      fullPath: '/api/public/cron/daily-content'
      preLoaderRoute: typeof ApiPublicCronDailyContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/auto-progress-phase': {
      id: '/api/public/cron/auto-progress-phase'
      path: '/api/public/cron/auto-progress-phase'
      fullPath: '/api/public/cron/auto-progress-phase'
      preLoaderRoute: typeof ApiPublicCronAutoProgressPhaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminAccountsRoute: typeof AdminAdminAccountsRoute
  AdminAdminAffiliateRoute: typeof AdminAdminAffiliateRoute
  AdminAdminAiContentRoute: typeof AdminAdminAiContentRoute
  AdminAdminChallengesRoute: typeof AdminAdminChallengesRoute
  AdminAdminDiscountsRoute: typeof AdminAdminDiscountsRoute
  AdminAdminPartnersRoute: typeof AdminAdminPartnersRoute
  AdminAdminPayoutsRoute: typeof AdminAdminPayoutsRoute
  AdminAdminPendingRoute: typeof AdminAdminPendingRoute
  AdminAdminPoolRoute: typeof AdminAdminPoolRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminSocialRoute: typeof AdminAdminSocialRoute
  AdminAdminTicketsRoute: typeof AdminAdminTicketsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAccountsRoute: AdminAdminAccountsRoute,
  AdminAdminAffiliateRoute: AdminAdminAffiliateRoute,
  AdminAdminAiContentRoute: AdminAdminAiContentRoute,
  AdminAdminChallengesRoute: AdminAdminChallengesRoute,
  AdminAdminDiscountsRoute: AdminAdminDiscountsRoute,
  AdminAdminPartnersRoute: AdminAdminPartnersRoute,
  AdminAdminPayoutsRoute: AdminAdminPayoutsRoute,
  AdminAdminPendingRoute: AdminAdminPendingRoute,
  AdminAdminPoolRoute: AdminAdminPoolRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminSocialRoute: AdminAdminSocialRoute,
  AdminAdminTicketsRoute: AdminAdminTicketsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedCommunityRouteChildren {
  AuthenticatedCommunitySlugRoute: typeof AuthenticatedCommunitySlugRoute
  AuthenticatedCommunityIndexRoute: typeof AuthenticatedCommunityIndexRoute
}

const AuthenticatedCommunityRouteChildren: AuthenticatedCommunityRouteChildren =
  {
    AuthenticatedCommunitySlugRoute: AuthenticatedCommunitySlugRoute,
    AuthenticatedCommunityIndexRoute: AuthenticatedCommunityIndexRoute,
  }

const AuthenticatedCommunityRouteWithChildren =
  AuthenticatedCommunityRoute._addFileChildren(
    AuthenticatedCommunityRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAffiliateRoute: typeof AuthenticatedAffiliateRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAffiliateRoute: AuthenticatedAffiliateRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AgreementRoute: AgreementRoute,
  BuyRoute: BuyRoute,
  DiscordRoute: DiscordRoute,
  LeaderboardRoute: LeaderboardRoute,
  PartnerApplyRoute: PartnerApplyRoute,
  PartnersRoute: PartnersRoute,
  RulesRoute: RulesRoute,
  ApiDeliverAccountRoute: ApiDeliverAccountRoute,
  ApiExchangeRateRoute: ApiExchangeRateRoute,
  ApiInitializePaymentRoute: ApiInitializePaymentRoute,
  ApiNotifyNewPurchaseRoute: ApiNotifyNewPurchaseRoute,
  ApiPartnerApplicationRoute: ApiPartnerApplicationRoute,
  ApiProvisionAccountRoute: ApiProvisionAccountRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
  ApiSquadWebhookRoute: ApiSquadWebhookRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiVerifyBankRoute: ApiVerifyBankRoute,
  ApiVerifyPaymentRoute: ApiVerifyPaymentRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  ApiAdminDeleteRequestRoute: ApiAdminDeleteRequestRoute,
  ApiAdminPoolRoute: ApiAdminPoolRoute,
  ApiAdminSetExchangeRateRoute: ApiAdminSetExchangeRateRoute,
  ApiPublicPushEventRoute: ApiPublicPushEventRoute,
  ApiPublicCronAutoProgressPhaseRoute: ApiPublicCronAutoProgressPhaseRoute,
  ApiPublicCronDailyContentRoute: ApiPublicCronDailyContentRoute,
  ApiPublicCronHandleNewsViolationRoute: ApiPublicCronHandleNewsViolationRoute,
  ApiPublicCronHandlePositionsViolationRoute:
    ApiPublicCronHandlePositionsViolationRoute,
  ApiPublicCronHandleScalpingRoute: ApiPublicCronHandleScalpingRoute,
  ApiPublicCronHandleWeekendViolationRoute:
    ApiPublicCronHandleWeekendViolationRoute,
  ApiPublicCronReconcilePaymentsRoute: ApiPublicCronReconcilePaymentsRoute,
  ApiPublicCronRefreshLeaderboardRoute: ApiPublicCronRefreshLeaderboardRoute,
  ApiPublicCronSyncEquityRoute: ApiPublicCronSyncEquityRoute,
  ApiPublicCronSyncEquityV2Route: ApiPublicCronSyncEquityV2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
